name: CI/CD

on:
  push:
    branches:
      - main
   pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci 
      - run: npm run test
      - run: echo SUCCESS